### ISSUE TITLE
official site crashed

### ISSUE THREAD

**Issue by huangbaitu123** [ScrapeGraphAI/scrapegraph-sdk#20]
Uncaught SyntaxError: Failed to execute 'appendChild' on 'Node': Identifier 'consent' has already been declared

layout-43a473a734a97554.js:1:12114

![image](https://github.com/user-attachments/assets/e2c9dd58-70aa-42ab-8da8-0c002739f892)

**Comment by VinciGit00** [comment]
send me the link please

**Comment by PeriniM** [comment]
Hey @huangbaitu123 can you please explain how you got the error? Which service were you trying to use? Is it related to the output schema?
Thanks

**Comment by gwpl** [comment]
Yes https://scrapegraphai.com/docs is down... but https://scrapegraph-doc.onrender.com/ is up ? Is it new adress?

**Comment by PeriniM** [comment]
Hey @gwpl, the corrected address is https://scrapegraphai.com/documentation, can you tell me where you found the /docs so I can fix It!

**Comment by gwpl** [comment]
Link I've found was search engine . You may like to update your README files:

* https://github.com/ScrapeGraphAI/scrapegraph-sdk/blob/8f3a87e880f820f4453d564fec02ef02af3742b3/README.md?plain=1#L76
* https://github.com/ScrapeGraphAI/scrapegraph-sdk/blob/8f3a87e880f820f4453d564fec02ef02af3742b3/README.md?plain=1#L20
*

**Comment by VinciGit00** [comment]
thank you,

i have updated it

**Comment by PeriniM** [comment]
Hey @gwpl, we updated all the links with the new documentation! Hope now it is clearer

[docs.scrapegraphai.com](https://docs.scrapegraphai.com)
